apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: user-pgimenez
spec:
  containers:
    - name: alpine
      # image: ghcr.io/pgimenez/weatherfetcher:latest
      image: alpine
      # command: ["python", "weather_data_fetcher.py"]
      command: ["sleep", "10000"]
      volumeMounts:
        - name: data-volume
          mountPath: /app/data
          subPath: weather/
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1"
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: data
