apiVersion: v1
kind: Pod
metadata:
  name: weather-fetcher-pod
  namespace: user-pgimenez
spec:
  containers:
    - name: weather-fetcher
      image: ghcr.io/pgimenez/datafetch:latest
      command: ["/bin/sh", "-c"]
      args: ["python weather_data_fetcher.py && sleep infinity"]
      volumeMounts:
        - name: data-volume
          mountPath: /app/data
          subPath: weather/
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1"
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: data
